---
- name: Make sure the Deluge container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "binhex/arch-delugevpn:latest"
    pull: yes
    networks:
      - name: swag_network
    privileged: yes
    sysctls:
      "net.ipv4.conf.all.src_valid_mark": "1"
    capabilities: 
      - net_admin
    state: 'started'
    env:
      "VPN_ENABLED": "no"
      "VPN_CLIENT": "wireguard"
      "VPN_PROV": "custom"
      "NAME_SERVERS": "{{ ','.join(deluge_nameservers) }}"
      "LAN_NETWORK": "172.20.0.0/16, {{ lan_network }}"
      "DELUGE_DAEMON_LOG_LEVEL": "info"
      "DELUGE_WEB_LOG_LEVEL": "info"
      "DEBUG": "true"
      "UMASK": "000"
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_home }}/{{ container_name }}:/config"
      - "{{ mergerfs_root }}/samba/media:/data"
      - "{{ mergerfs_root }}/samba/images:/images"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "8118:8118"
      - "58846:58846"
      - "59846:58946"
    restart_policy: unless-stopped

