# Docker stuff
docker_install_compose: true
docker_home: "/opt/docker/data"

# Network
lan_network: "10.0.1.0/24"
dns_nameservers: ['10.0.1.1']
deluge_nameservers: ['1.1.1.1', '1.0.0.1']

# System
guid: '1000'
timezone: 'Europe/Sofia'
hostname: '{{ inventory_hostname }}'
username: zerw
shell: /usr/bin/fish
dotfiles_repo: "https://github.com/zerw0/dots"

# Swag
domain: ''
email: ''
cf_email: ''

# Wireguard
wireguard_dns: "10.0.1.1"
wireguard_host: ""

# Vaultwarden
vaultwarden_url: ""

# Databases
postgres_db: "bitwarden"
postgres_user: "bitwarden"

# NTPD
ntp_timezone: '{{ timezone }}'

# Smartd email
mail_recipients: '{{ email }}'

# Locale
locale: en_US.UTF-8

# Security
security_ssh_port: 8888
security_sudoers_passwordless: ['{{ username }}']
security_autoupdate_reboot: true
security_autoupdate_mail_to: '{{ email }}'
security_autoupdate_reboot_time: '03:00'
security_autoupdate_mail_on_error: false
security_ssh_permit_root_login: "no"

security_fail2ban_enabled: true 
enable_endlessh: true

# NAS Stuff
mergerfs_root: /mnt/storage
enable_nas: true
enable_hdidle: true
spindown_time: 600

disks:
        - { path: /mnt/disk1, src: /dev/disk/by-uuid/90b30d2f-2ac8-4606-bd5e-f936ee4dec05, content: true }
        - { path: /mnt/disk2, src: /dev/disk/by-uuid/a937736f-c4de-4125-9df6-8e56799ab8d1, content: true }

# Samba
enable_samba: true
samba_server_string: '{{ hostname }}'
samba_global_include: global-include.conf
samba_mitigate_cve_2017_7494: false
samba_server_max_protocol: 'SMB3'
samba_server_min_protocol: 'SMB3'

samba_shares:
    - name: main
      guest_ok: no
      public: no
      read_only: no
      writable: yes
      owner: '{{ username }}'
      browseable: yes
      path: '{{ mergerfs_root }}/samba/main'
      valid_users: '{{ username }}'
      write_list: '{{ username }}'

    - name: media
      guest_ok: no
      public: no
      read_only: no
      writable: yes
      owner: '{{ username }}'
      browseable: yes
      path: '{{ mergerfs_root }}/samba/media'
      valid_users: '{{ username }}'
      write_list: '{{ username }}'

    - name: images
      guest_ok: no
      public: no
      read_only: no
      writable: yes
      owner: '{{ username }}'
      browseable: yes
      path: '{{ mergerfs_root }}/samba/images'
      valid_users: '{{ username }}'
      write_list: '{{ username }}'

    - name: games
      guest_ok: no
      public: no
      read_only: no
      writable: yes
      owner: '{{ username }}'
      browseable: yes
      path: '{{ mergerfs_root }}/samba/games'
      valid_users: '{{ username }}'
      write_list: '{{ username }}'

# Packages
extra_packages:
    - fish
    - htop
    - exa
    - fd-find
    - bat
    - mc
    - ranger

# Services
enable_vaultwarden: false
enable_nextcloud: false
enable_kavita: false
enable_flame: false
enable_dashy: false

# System
enable_prowlarr: false
enable_watchtower: false
enable_duplicati: false
enable_syncthing: false
enable_netbootxyz: false
enable_starship: true

# Cockpit
enable_cockpit: true
cockpit_started: yes

# Media
enable_sonarr: false
enable_deluge: false
enable_radarr: false
enable_jellyfin: false
enable_metube: false
enable_navidrome: false
enable_bazarr: false

# Monitoring
enable_gotify: false
enable_scrutiny: false
enable_prometheus: true
enable_grafana: false
enable_node_exporter: true

# Network
enable_swag: false
enable_wireguard: false

# Games
enable_ps3netsrv: false
enable_ps2smb: false

# Home Automation
enable_homeassistant: false