---
- name: Make sure the Wireguard container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "weejewel/wg-easy"
    pull: yes
    networks:
      - name: swag_network
    sysctls:
      "net.ipv4.conf.all.src_valid_mark": "1"
      "net.ipv4.ip_forward": "1"
    capabilities:
      - net_admin
      - sys_module
    state: "started"
    env:
      "WG_HOST": "{{ wireguard_host }}"
      "WG_DEFAULT_DNS": "{{ wireguard_dns }}"
      "WG_PASSWORD": "{{ wireguard_password }}"
    ports:
      - "51820:51820/udp"
    volumes:
      - "{{ docker_home }}/{{ container_name }}:/etc/wireguard"
    restart_policy: unless-stopped
