---
- name: Make sure the Kavita container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "kizaing/kavita:latest"
    pull: yes
    networks:
      - name: swag_network
    state: "started"
    env:
      "TZ": "{{ timezone }}"
    volumes:
      - "{{ docker_home }}/{{ container_name }}:/kavita/config"
      - "{{ mergerfs_root }}/samba/media/manga:/manga"
      - "{{ mergerfs_root }}/samba/media/books:/books"
    ports: 
      - "5000:5000"
    restart_policy: unless-stopped
