---
- name: Make sure the Duplicati container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "ghcr.io/linuxserver/duplicati"
    pull: yes
    networks:
      - name: swag_network
    state: "started"
    env:
      "TZ": "{{ timezone }}"
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
    volumes:
      - "{{ docker_home }}/{{ container_name }}:/config"
      - "{{ docker_home }}/vaultwarden:/source/bitwarden:ro"
      - "{{ docker_home }}/vaultwarden-postgres:/source/psql:ro"
    restart_policy: unless-stopped
