---
- name: Make sure the Flame container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "pawelmalak/flame:latest"
    pull: yes
    networks:
      - name: swag_network
    state: "started"
    env:
      "PASSWORD": "{{ flame_password }}"
    volumes:
      - "{{ docker_home }}/{{ container_name }}:/app/data"
    restart_policy: unless-stopped
