---
- name: Make sure the Watchtower container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "containrrr/watchtower"
    pull: yes
    state: 'started'
    env:
      'TZ': 'timezone'
      'WATCHTOWER_CLEANUP': 'true'
      'WATCHTOWER_INCLUDE_STOPPED': 'true'
      'WATCHTOWER_REVIVE_STOPPED': 'true'
      'WATCHTOWER_POLL_INTERVAL': '7200'
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart_policy: unless-stopped

