---
- name: Make sure the {{ container_name }} container is created and running
  docker_container:
      name: '{{ container_name }}'
      image: 'homeassistant/home-assistant:stable'
      networks:
          - name: swag_network
      pull: yes
      state: 'started'
      env:
          'TZ': '{{ timezone }}'
      volumes:
          - '{{ docker_home }}/{{ container_name }}/config:/config'
      restart_policy: unless-stopped