---
- name: Make sure the Bazarr container is created and running
  docker_container:
    name: "{{ container_name }}"
    image: "lscr.io/linuxserver/bazarr:latest"
    pull: yes
    networks:
      - name: swag_network
    state: "started"
    env:
      "TZ": "{{ timezone }}"
      "PUID": "{{ guid }}"
      "PGID": "{{ guid }}"
    volumes:
      - "{{ docker_home }}/{{ container_name }}:/config"
      - "{{ mergerfs_root}}/samba/media:/data"
    restart_policy: unless-stopped
